//
//  ListOfTrainStations.swift
//  TripView Clone
//
//  Created by Thomas Sesselmann on 11/04/2015.
//  Copyright (c) 2015 Thomas Sesselmann. All rights reserved.
//

import Foundation

func getListOfTrainStations() -> [[String]] {

    let orderedListOfTrainStations = [
        "Allawah",
        "Arncliffe",
        "Artarmon",
        "Ashfield",
        "Asquith",
        "Auburn",
        "Banksia",
        "Bankstown",
        "Bardwell Park",
        "Beecroft",
        "Belmore",
        "Berala",
        "Berowra",
        "Beverly Hills",
        "Bexley North",
        "Birrong",
        "Blacktown",
        "Bondi Junction",
        "Burwood",
        "Cabramatta",
        "Camellia",
        "Campbelltown",
        "Campsie",
        "Canley Vale",
        "Canterbury",
        "Caringbah",
        "Carlingford",
        "Carlton",
        "Carramar",
        "Casula",
        "Central",
        "Chatswood",
        "Cheltenham",
        "Chester Hill",
        "Circular Quay",
        "Clarendon",
        "Clyde",
        "Carlingford",
        "Clyde",
        "Clyde Junction",
        "Como",
        "Concord West",
        "Cronulla",
        "Croydon",
        "Denistone",
        "Domestic Airport",
        "Doonside",
        "Dulwich Hill",
        "Dundas",
        "East Hills",
        "East Richmond",
        "Eastwood",
        "Edgecliff",
        "Edmondson Park",
        "Emu Plains",
        "Engadine",
        "Epping",
        "Fairfield",
        "Flemington",
        "Glenfield",
        "Gordon",
        "Granville",
        "Green Square",
        "Guildford",
        "Gymea",
        "Harris Park",
        "Heathcote",
        "Holsworthy",
        "Homebush",
        "Hornsby",
        "Hornsby Junction",
        "Hurlstone Park",
        "Hurstville",
        "Ingleburn",
        "International Airport",
        "Jannali",
        "Killara",
        "Kings Cross",
        "Kingsgrove",
        "Kingswood",
        "Kirrawee",
        "Kogarah",
        "Lakemba",
        "Leightonfield",
        "Leppington",
        "Leumeah",
        "Lewisham",
        "Lidcombe",
        "Lindfield",
        "Liverpool",
        "Loftus",
        "Macarthur",
        "Macdonaldtown",
        "Macquarie Fields",
        "Macquarie Park",
        "Macquarie University",
        "Marayong",
        "Marrickville",
        "Martin Place",
        "Mascot",
        "Meadowbank",
        "Merrylands",
        "Milsons Point",
        "Minto",
        "Miranda",
        "Mortdale",
        "Mount Colah",
        "Mount Druitt",
        "Mount Kuring-gai",
        "Mulgrave",
        "Museum",
        "Narwee",
        "Newtown",
        "Normanhurst",
        "North Strathfield",
        "North Sydney",
        "North Ryde",
        "Oatley",
        "Olympic Park",
        "Padstow",
        "Panania",
        "Parramatta",
        "Pendle Hill",
        "Pennant Hills",
        "Penrith",
        "Penshurst",
        "Petersham",
        "Punchbowl",
        "Pymble",
        "Quakers Hill",
        "Redfern",
        "Regents Park",
        "Revesby",
        "Rhodes",
        "Richmond",
        "Riverstone",
        "Riverwood",
        "Rockdale",
        "Rooty Hill",
        "Rosehill",
        "Roseville",
        "Rydalmere",
        "Schofields",
        "Sefton",
        "Seven Hills",
        "St James",
        "St Leonards",
        "St Marys",
        "St Peters",
        "Stanmore",
        "Strathfield",
        "Summer Hill",
        "Sutherland",
        "Sydenham",
        "Telopea",
        "Tempe",
        "Thornleigh",
        "Toongabbie",
        "Town Hall",
        "Turramurra",
        "Turrella",
        "Villawood",
        "Vineyard",
        "Wahroonga",
        "Waitara",
        "Warrawee",
        "Warwick Farm",
        "Waterfall",
        "Waverton",
        "Wentworthville",
        "Werrington",
        "West Ryde",
        "Westmead",
        "Wiley Park",
        "Windsor",
        "Wolli Creek",
        "Wollstonecraft",
        "Woolooware",
        "Wynyard",
        "Yagoona",
        "Yennora"
    ]
        
    var currentLetter : Character = "A"
    
    var resultList : [[String]] = []
    var tempList : [String] = []
    
    for name in orderedListOfTrainStations {
        let firstLetterInName = name[name.startIndex]
        if firstLetterInName != currentLetter {
            resultList += [tempList]
            tempList.removeAll(keepCapacity: false)
            currentLetter = firstLetterInName
        }
        
        tempList += [name]
    }
    
    return resultList
    
}